.TH ECHO_SUCCESSMSG 1 2023-Jul "" "echo back the success message data to the desktop client"
.SH NAME
echo_successMsg \- echo_successMsg(data,
    <i>code</i> = 0)
.SH SYNOPSIS
\fIecho_successMsg(data,
    <i>code</i> = 0)\fR
.SH OPTIONS
.PP
\fBdata\fB \fR\- . any kind of the R# data object, the object data will be encoded as json string automatically in this function
.PP
.PP
\fBcode\fB \fR\- 0. 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.echo_successMsg at restHost.R:line 10
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2023
