.TH FS.EC_NUMBERS_FASTA 1 2022-10-29 "" "get file path of the fasta file for EC number annotation"
.SH NAME
fs.ec_numbers_fasta \- fs.ec_numbers_fasta()
.SH SYNOPSIS
\fIfs.ec_numbers_fasta()\fR
.SH FILES
.PP
SMRUCC/R#.declare_function.fs.ec_numbers_fasta at fs.R:line 5
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2022
