.TH FS.SUBCELLULAR_LOCATIONS_FASTA 1 2022-11-08 "" "get file path of the fasta file for subcellular locations"
.SH NAME
fs.subcellular_locations_fasta \- fs.subcellular_locations_fasta()
.SH SYNOPSIS
\fIfs.subcellular_locations_fasta()\fR
.SH FILES
.PP
SMRUCC/R#.declare_function.fs.subcellular_locations_fasta at fs.R:line 11
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2022
