.TH MATRIXFILEREADER 1 2022-10-17 "" "matrixFileReader"
.SH NAME
matrixFileReader \- matrixFileReader(file,
    <i>z.score</i> = TRUE)
.SH SYNOPSIS
\fImatrixFileReader(file,
    <i>z.score</i> = TRUE)\fR
.SH OPTIONS
.PP
\fBfile\fB \fR\- . 
.PP
.PP
\fBz.score\fB \fR\- TRUE. 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.matrixFileReader at expr_matrix.R:line 2
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2022
