.TH MATRIXFILEREADER 1 2023-Jul "" "Helper for read expression matrix file"
.SH NAME
matrixFileReader \- matrixFileReader(file,
    <i>z.score</i> = <span style='color: blue;'>TRUE</span>)
.SH SYNOPSIS
\fImatrixFileReader(file,
    <i>z.score</i> = <span style='color: blue;'>TRUE</span>)\fR
.SH OPTIONS
.PP
\fBfile\fB \fR\- . the file path of the target expression matrix file, data reader is distinct from the file extension suffix name: + csv: a plain text csv table file + hts: a binary data matrix of the expression data
.PP
.PP
\fBz.score\fB \fR\- TRUE. 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.matrixFileReader at expr_matrix.R:line 12
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2023
