.\" man page create by R# package system.
.TH MODELLER 1 2000-1月 "build_metabolic_network" "build_metabolic_network"
.SH NAME
build_metabolic_network \- 
.SH SYNOPSIS
\fIbuild_metabolic_network(\fBproj\fR as string, 
\fBrhea\fR as <generic> RheaNetworkReader);\fR
.SH SEE ALSO
Modeller
.SH FILES
.PP
GCModellerDesktop.dll
.PP
