.\" man page create by R# package system.
.TH MODELLER 1 2000-01-01 "extract_proteinset_fasta" "extract_proteinset_fasta"
.SH NAME
extract_proteinset_fasta \- 
.SH SYNOPSIS
\fIextract_proteinset_fasta(\fBproj\fR as string, 
\fBsave\fR as string);\fR
.SH SEE ALSO
Modeller
.SH FILES
.PP
GCModellerDesktop.dll
.PP
