.\" man page create by R# package system.
.TH MODELLER 1 2000-1月 "save_enzyme_annotation" "save_enzyme_annotation"
.SH NAME
save_enzyme_annotation \- 
.SH SYNOPSIS
\fIsave_enzyme_annotation(\fBproj\fR as string, 
\fBanno\fR as string);\fR
.SH SEE ALSO
Modeller
.SH FILES
.PP
GCModellerDesktop.dll
.PP
