.\" man page create by R# package system.
.TH MODELLER 1 2000-1月 "save_subcellular_location" "save_subcellular_location"
.SH NAME
save_subcellular_location \- 
.SH SYNOPSIS
\fIsave_subcellular_location(\fBproj\fR as string, 
\fBanno\fR as string);\fR
.SH SEE ALSO
Modeller
.SH FILES
.PP
GCModellerDesktop.dll
.PP
